
SOURCES = [
	'file_test.c',
	'all_tests.c',
	'seatest/seatest.c'
]


def options (opt):
	opt.load ('compiler_c')


def configure (conf):
	conf.load ('compiler_c')


def build (bld):
	bld.program (
		source = SOURCES,
		target = 'test',
		includes = ['.', '../include'],
		use = ['xgod'],
		rpath = bld.env.XGOD_RPATH
	)


def test (ctx):
	# use subprocess instead of waf rules so we can get the pretty shell colours
	import subprocess
	subprocess.call ([ctx.path.get_bld().abspath() + "/test"])