
SOURCES = ['file.c', 'sha1.c']


def options (opt):
	opt.load ('compiler_c')

def configure (conf):
	conf.load ('compiler_c')

def build (bld):
	bld.shlib (
		features = 'c',
		source = SOURCES,
		includes = '../include ../include/xgod',
		target = 'xgod',
	)
	
	bld.env.XGOD_RPATH = [bld.path.get_bld().abspath()]
